name: Test Build

on:
  push:
    branches:
    - main
    - workflow
  pull_request:
    branches:
    - main
    - workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: devcontainers/ci@v0.3

    - name: Test
      run: ls
